version: 2.1 # use CircleCI 2.1

defaults: &defaults
  working_directory: ~/node-k8s
  
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1

jobs: # a collection of steps
  test: # runs not using Workflows must have a `build` job as entry point
    <<: *defaults
    docker:
      - image: "cimg/base:stable"
    steps: 
      - node/install
      - checkout # special step to check out source code to working directory

      - run:
          name: install
          command: npm install

      - run: # run test
          name: test
          command: npm run test

      - run: # run builf
          name: build
          command: npm run build

workflows:
  test_build:
    jobs:
      - test
